name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system packages
      run: |
        sudo apt update
        sudo apt install -y \
          python3 python3-pip python3-setuptools \
          openjdk-17-jdk git zip unzip \
          libffi-dev libssl-dev autoconf automake libtool

    - name: Install Python packages
      run: |
        pip3 install --upgrade pip
        pip3 install cython==0.29.33
        pip3 install buildozer

        buildozer version || true

    - name: Build APK
      run: |
        echo ">>> Starting Buildozer..."
        buildozer -v android debug

    - name: Upload APK
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
