name: Kivy APK Builder

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk unzip git

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Show directory (debug)
        run: ls -R .

      - name: Build APK (DEBUG)
        run: |
          set -x
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
